openapi: 3.0.3
info:
  title: Introducción
  description: |-
    Para la implementación de la **Facturación Electrónica**, la SUNAT ha puesto a su disposición diversos manuales y documentos técnicos, los cuales inicialmente son complejos de entender y utilizar.

    La api le permitirá generar diversos documentos electrónicos, y de cada uno obtendrá los 3 archivos indispensables **(XML Firmado, Documento PDF, y CDR)**.

    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.demo3pro6.ibu.pe
tags:
  - name: api
    description: Generador de facturas
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/documents/updatedocumentstatus:
    post:
      tags:
        - api
      summary: ACTUALIZAR ESTADO DEL DOCUMENTO
      description: |  
        ***Ejemplo:***  
         - **Método:** POST  
         - **URL:** https://demo.pro5.fastura.app/api/documents/updatedocumentstatus  
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt
      operationId: updatedocumentstatus
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: |
            JSON RESPUESTA  

            **Nota Importante:** Para completar **state_type_id** tiene que tomar en cuenta la lista de estados de un documento:  

            - 05: Aceptado
            - 11: Anulado
            - 03: Enviado
            - 07: Observado
            - 13: Por anular
            - 09: Rechazados
            - 01: Registrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - fastura_auth:
            - write
            - read 
          
#Formato Json de ACTUALIZAR ESTADO DEL DOCUMENTO
components:
  schemas:
    Pet:
      type: object
      properties:
        externail_id:
          type: string
          example: "2dded172-cd17-4078-9c88-10a9b1177f2d"
        state_type_id:
          type: string
          example: "01"

      required:
        - external_id
        - state_type_id

    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.demo3pro6.ibu.pe
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header