openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.demo3pro6.ibu.pe
tags:
  - name: api
    description: Generar Cotización
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/items/6/update:
    post:
      tags:
        - api
      summary: ACTUALIZAR PRODUCTOS 
      description: |  
        ***Ejemplo:***  
         - **Método:** POST
         - **URL:** https://empresa1.demo3pro6.ibu.pe/api/items/{{item_id}}/update  
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt

        **IMPORTANTE:**  
        Reemplace el item_id por el id del producto  

        **EJEMPLO:**  
        En este caso actualizaremos el producto con id #6.

      operationId: actualizarProductos
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: |
            JSON RESPUESTA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - fastura_auth:
            - write
            - read 
          
# Formato Json de ACTUALIZAR PRODUCTOS
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: number
          example: 6
        item_type_id: 
          type: string
          example: "01"
        internal_id:
          type: string
          example: "rrr"
        item_code:
          type: string
          example: "new_code"
        item_code_gs1:
          type: string
          example:
        description:
          type: string
          example: "apk"
        name:
          type: string
          example: "apk"
        second_name:
          type: string
          example:
        unit_type_id:
          type: string
          example: "NIU"
        currency_type_id:
          type: string
          example: "PEN"
        sale_unit_price:
          type: string
          example: "500"
        purchase_unit_price:
          type: number
          example: 0
        has_isc:
          type: boolean
          example: false
        system_isc_type_id:
          type: string
          example:
        percentage_isc:
          type: number
          example: 0
        suggested_price:
          type: number
          example: 0
        sale_affectation_igv_type_id:
          type: string
          example: "10"
        purchase_affectation_igv_type_id:
          type: string
          example: "10"
        calculate_quantity:
          type: boolean
          example: false
        stock:
          type: number
          example: 0
        stock_min:
          type: number
          example: 0
        has_igv:
          type: boolean
          example: true
        has_perception:
          type: boolean
          example: false
        item_unit_types:
          type: string
          example: []
        percentage_of_profit:
          type: number
          example: 0
        percentage_perception:
          type: number
          example: 0
        image:
          type: string
          example:
        image_url:
          type: string
          example:
        temp_path:
          type: string
          example:
        is_set:
          type: boolean
          example: false
        account_id:
          type: string
          example:
        category_id:
          type: string
          example:
        brand_id:
          type: string
          example:
        date_of_due:
          type: string
          example:
        lot_code:
          type: string
          example:
        lots_enabled:
          type: boolean
          example: false
        lots:
          type: string
          example: []
        
      

    Response:
      type: object
      properties:
        succes:
          type: boolean
          example: true
        msg:
          type: string
          example: "Producto editado con éxito"
        data:
          type: object
          properties:
            id:
              type: number 
              example: 6
            item_id:
              type: number
              example: 6
            name:
              type: string
              example: "ALERFORT"
            full_description:
              type: string
              example: "rrr - apk"
            description:
              type: string
              example: "apk"
            currency_type_id:
              type: string
              example: "PEN"
            internal_id:
              type: string
              example: "rrr"
            item_code:
              type: string
              example: "new_code"
            currency_type_symbol:
              type: string
              example: "S/"
            sale_unit_price:
              type: string
              example: "500.00"
            purchase_unit_price:
              type: number
              example: 0
            unit_type_id:
              type: string
              example: "NIU"
            sale_affectation_igv_type_id:
              type: string
              example: "10"
            purchase_affectation_igv_type_id:
              type: string
              example: "10"
            calculate_quantity:
              type: boolean
              example: false
            has_igv:
              type: boolean
              example: true
            is_set:
              type: boolean
              example: false
            aux_quantity:
              type: number
              example: 1
           

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.demo3pro6.ibu.pe
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header