openapi: 3.0.3
info:
  title: API de Mensajería
  description: Endpoint para enviar archivos multimedia a través de WhatsApp.
  version: 1.0.0

servers:
  - url: https://demo.qr.uio.la
    description: Servidor de producción

tags:
  - name: api
    description: Enviar Multimedia

paths:
  /api/message/send-media:
    post:
      tags:
        - api
      summary: Enviar archivo multimedia por WhatsApp
      operationId: enviarMultimedia
      description: Permite enviar imágenes, videos o audios a un número de WhatsApp.
      requestBody:
        description: Datos necesarios para enviar el archivo multimedia.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnviarMultimediaRequest"
      responses:
        "200":
          description: Multimedia enviado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Error en la solicitud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: No autorizado (Token incorrecto o ausente)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    EnviarMultimediaRequest:
      type: object
      properties:
        media:
          type: string
          enum: [image, video, audio]
          example: "image"
          description: Tipo de archivo multimedia.
        caption:
          type: string
          example: "Plain Text message"
          description: Mensaje de texto acompañando el archivo.
        link:
          type: string
          example: "https://...."
          description: URL o Base64 del archivo multimedia.
        number:
          type: string
          example: "51123456789"
          description: Número de teléfono en formato internacional sin el "+".
    
    SuccessResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            key:
              type: object
              properties:
                remoteJid:
                  type: string
                  example: "51123456789@s.whatsapp.net"
                fromMe:
                  type: boolean
                  example: true
                id:
                  type: string
                  example: "3EB0CAF5AF1C92781BFD84"
            message:
              type: object
              properties:
                imageMessage:
                  type: object
                  properties:
                    url:
                      type: string
                      example: "https://mmg.whatsapp.net/..."
                    mimetype:
                      type: string
                      example: "image/png"
                    caption:
                      type: string
                      example: "Plain Text message"
                    fileSha256:
                      type: string
                      example: "ti3hY4w6Rx9QNRhaqBLENIrjB2cam5UzGCJZQRCU1Eo="
                    fileLength:
                      type: integer
                      example: 4397
                    mediaKey:
                      type: string
                      example: "4WrvwBFE0olXpJOct8eQGKK0pcdgt9dHAinXy9nyCnE="
                    fileEncSha256:
                      type: string
                      example: "1aNj9y6YoNDz4jblhGqRXDCxHGZBf4HCwPNL4wC8kkI="
                    directPath:
                      type: string
                      example: "/o1/v/t62...."
                    mediaKeyTimestamp:
                      type: string
                      example: "1731950781"
                    contextInfo:
                      type: array
                      items:
                        type: object
            messageTimestamp:
              type: string
              example: "1731950893"
            status:
              type: string
              example: "PENDING"
    
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Descripción del error"
