openapi: 3.0.3
info:
  title: Introducción
  description: |-
    Para la implementación de la **Facturación Electrónica**, la SUNAT ha puesto a su disposición diversos manuales y documentos técnicos, los cuales inicialmente son complejos de entender y utilizar.

    La api le permitirá generar diversos documentos electrónicos, y de cada uno obtendrá los 3 archivos indispensables **(XML Firmado, Documento PDF, y CDR)**.

    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.demo3pro6.ibu.pe
tags:
  - name: api
    description: Generador de facturas
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/documents:
    post:
      tags:
        - api
      summary: FACTURA GRAVADA EN DÓLARES
      description: |

        ***Ejemplo:***  
         - **Método:** POST  
         - **URL:** https://demo.pro5.fastura.app/api/documents  
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt
      operationId: facturaGravadaDolares
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: JSON RESPUESTA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - petstore_auth:
            - write:pets
            - read:pets
          
# Formato Json de FACTURA GRAVADA EN DÓLARES
components:
  schemas:
    Pet:
      type: object
      properties:
        serie_documento:
          type: string
          example: "F001"
        numero_documento:
          type: string
          example: "#"
        fecha_de_emision:
          type: string
          format: date
          example: "2018-10-09"
        hora_de_emision:
          type: string
          format: time
          example: "10:11:11"
        codigo_tipo_operacion:
          type: string
          example: "0101"
        codigo_tipo_documento:
          type: string
          example: "01"
        codigo_tipo_moneda:
          type: string
          example: "USD"
        fecha_de_vencimiento:
          type: string
          format: date
          example: "2018-10-09"
        numero_orden_de_compra:
          type: string
          example: "0045467898"
        datos_del_cliente_o_receptor:
          type: object
          properties:
            codigo_tipo_documento_identidad:
              type: string
              example: "6"
            numero_documento:
              type: string
              example: "10414711225"
            apellidos_y_nombres_o_razon_social:
              type: string
              example: "EMPRESA XYZ S.A."
            codigo_pais:
              type: string
              example: "PE"
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "Av. 2 de Mayo"
            correo_electronico:
              type: string
              example: "demo@gmail.com"
            telefono:
              type: string
              example: "427-1148"
        totales:
          type: object
          properties:
            total_exportacion:
              type: number
              format: float
              example: 0.00
            total_operaciones_gravadas:
              type: number
              format: float
              example: 100.00
            total_operaciones_inafectas:
              type: number
              format: float
              example: 0.00
            total_operaciones_exoneradas:
              type: number
              format: float
              example: 0.00
            total_operaciones_gratuitas:
              type: number
              format: float
              example: 0.00
            total_igv:
              type: number
              format: float
              example: 18.00
            total_impuestos:
              type: number
              format: float
              example: 18.00
            total_valor:
              type: number
              format: float
              example: 100.00
            total_venta:
              type: number
              format: float
              example: 118.00
        items:
          type: array
          items:
            type: object
            properties:
              codigo_interno:
                type: string
                example: "P0121"
              descripcion:
                type: string
                example: "Inca Kola 250 ml"
              codigo_producto_sunat:
                type: string
                example: ""
              unidad_de_medida:
                type: string
                example: "NIU"
              cantidad:
                type: integer
                format: int32
                example: 2
              valor_unitario:
                type: number
                format: float
                example: 50.00
              codigo_tipo_precio:
                type: string
                example: "01"
              precio_unitario:
                type: number
                format: float
                example: 59.00
              codigo_tipo_afectacion_igv:
                type: string
                example: "10"
              total_base_igv:
                type: number
                format: float
                example: 100.00
              porcentaje_igv:
                type: number
                format: float
                example: 18.00
              total_igv:
                type: number
                format: float
                example: 18.00
              total_impuestos:
                type: number
                format: float
                example: 18.00
              total_valor_item:
                type: number
                format: float
                example: 100.00
              total_item:
                type: number
                format: float
                example: 118.00
            
      required:
        - serie_documento
        - numero_documento
        - fecha_de_emision
        - hora_de_emision
        - codigo_tipo_operacion
        - codigo_tipo_documento
        - codigo_tipo_moneda
        - fecha_de_vencimiento
        - datos_del_cliente_o_receptor
        - totales
        - items

    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            number:
              type: string
              example: "F001-29"
            filename:
              type: string
              example: "20302019010-01-F001-29"
            external_id:
              type: string
              example: "2bb69425-77e0-4566-8150-08f7828ea189"
            state_type_id:
              type: string
              example: "05"
            state_type_description:
              type: string
              example: "Aceptado"
            number_to_letter:
              type: string
              example: "Ciento dieciocho con 00/100"
            hash:
              type: string
              example: "L4SMnLskkHwi02oy6a4tqcRMv0Y="
            qr:
              type: string
              example: "iVBORw0KGgoAAAANSUhEUgAAAJYAAACWCAIAAACzY+a1AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAgAElEQVR4AQCbgGR/Af///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALZZrzNrOjhXAAAAAElFTkSuQmCC"
            id:
              type: integer
              example: 324
        links:
          type: object
          properties:
            xml:
              type: string
              example: "https://demo.pro5.fastura.app/downloads/document/xml/2bb69425-77e0-4566-8150-08f7828ea189"
            pdf:
              type: string
              example: "https://demo.pro5.fastura.app/downloads/document/pdf/2bb69425-77e0-4566-8150-08f7828ea189"
            cdr:
              type: string
              example: "https://demo.pro5.fastura.app/downloads/document/cdr/2bb69425-77e0-4566-8150-08f7828ea189"
        response:
          type: object
          properties:
            code:
              type: string
              example: "0"
            description:
              type: string
              example: "La Factura numero F001-29, ha sido aceptada"
            notes:
              type: array
              items:
                type: string
              example: [] 

      required:
        - data
        - responde

  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.demo3pro6.ibu.pe
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header