openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.demo3pro6.ibu.pe
tags:
  - name: api
    description: Generar Notas
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/documents:
    post:
      tags:
        - api
      summary: NOTA CRÉDITO - FACTURA
      description: |  
        Una nota de crédito es un documento legal que se utiliza en transacciones de compraventa donde interviene un descuento posterior a la emisión de la factura, una anulación total, un cobro de un gasto incurrido de más, devolución de bienes.    
        
        ***Ejemplo:***  
         - **Método:** POST  
         - **URL:** https://empresa1.demo3pro6.ibu.pe/api/documents  
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt
      operationId: notaCredito_factura
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: |
            JSON RESPUESTA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - fastura_auth:
            - write
            - read 
          
# Formato Json de NOTA CRÉDITO - FACTURA
components:
  schemas:
    Pet:
      type: object
      properties:
        serie_documento:
          type: string
          example: "FC01"
        numero_documento:
          type: string
          example: "#"
        fecha_de_emision:
          type: string
          format: date
          example: "2024-11-05"
        hora_de_emision:
          type: string
          format: time
          example: "10:11:11"
        codigo_tipo_documento:
          type: string
          example: "07"
        codigo_tipo_nota:
          type: string
          example: "01"
        motivo_o_sustento_de_nota:
          type: string
          example: "Error al emitir comprobante"
        codigo_tipo_moneda:
          type: string
          example: "PEN"
        numero_orden_de_compra:
          type: string
          example: "0045467898"
        documento_afectado:
          type: object
          properties:
            external_id:
              type: string
              example: "a7d75ecc-061d-46f6-8ee4-2521a5bbec1d"
        datos_del_cliente_o_receptor:
          type: object
          properties:
            codigo_tipo_documento_identidad:
              type: string
              example: "6"
            numero_documento:
              type: string
              example: "10414711225"
            apellidos_y_nombres_o_razon_social:
              type: string
              example: "EMPRESA XYZ S.A."
            codigo_pais:
              type: string
              example: "PE"
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "Av. 2 de Mayo"
            correo_electronico:
              type: string
              example: "demo@gmail.com"
            telefono:
              type: string
              example: "427-1148"
        totales:
          type: object
          properties:
            total_exportacion:
              type: number
              format: float
              example: 0.00
            total_operaciones_gravadas:
              type: number
              format: float
              example: 100.00
            total_operaciones_inafectas:
              type: number
              format: float
              example: 0.00
            total_operaciones_exoneradas:
              type: number
              format: float
              example: 0.00
            total_operaciones_gratuitas:
              type: number
              format: float
              example: 0.00
            total_igv:
              type: number
              format: float
              example: 18.00
            total_impuestos:
              type: number
              format: float
              example: 18.00
            total_valor:
              type: number
              format: float
              example: 100.00
            total_venta:
              type: number
              format: float
              example: 118.00
        items:
          type: array
          items:
            type: object
            properties:
              codigo_interno:
                type: string
                example: "P0121"
              descripcion:
                type: string
                example: "Inca Kola 250 ml"
              codigo_producto_sunat:
                type: string
                example: ""
              unidad_de_medida:
                type: string
                example: "NIU"
              cantidad:
                type: integer
                format: int32
                example: 2
              valor_unitario:
                type: number
                format: float
                example: 50.00
              codigo_tipo_precio:
                type: string
                example: "01"
              precio_unitario:
                type: number
                format: float
                example: 59.00
              codigo_tipo_afectacion_igv:
                type: string
                example: "10"
              total_base_igv:
                type: number
                format: float
                example: 100.00
              porcentaje_igv:
                type: number
                format: float
                example: 18.00
              total_igv:
                type: number
                format: float
                example: 18.00
              total_impuestos:
                type: number
                format: float
                example: 18.00
              total_valor_item:
                type: number
                format: float
                example: 100.00
              total_item:
                type: number
                format: float
                example: 118.00
          item:
            type:array

      required:
        - serie_documento
        - fecha_de_emision
        - codigo_tipo_documento
        - fecha_de_vencimiento
        - codigo_tipo_documento_identidad
        - external_id
        - numero_documento
    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            number:
              type: string
              example: "FC01-3"
            filename:
              type: string
              example: "11111111111-07-FC01-3"
            external_id:
              type: string
              example: "6269dbe8-9b32-4d43-b42f-81594a0a36cf"
            state_type_id:
              type: string
              example: "05"
            state_type_description:
              type: string
              example: "Aceptado"
            number_to_letter:
              type: string
              example: "Ciento dieciocho con 00/100"
            hash:
              type: string
              example: "53iYvXndao4sSUP8XKrA/2aSjYk="
            qr:
              type: string
              example: "iVBORw0KGgoAAAANSUhEUgAAAJYAAACWCAIAAACzY+a1AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAgAElEQVR4AQCbgGR/Af///wAAAMPNxEJsyosTAAAAAElFTkSuQmCC"
            id:
              type: integer
              example: 554
            print_ticket:
              type: string
              example: "https://empresa1.demo3pro6.ibu.pe/print/document/6269dbe8-9b32-4d43-b42f-81594a0a36cf/ticket"
        links:
          type: object
          properties:
            xml:
              type: string
              example: "https://empresa1.demo3pro6.ibu.pe/downloads/document/xml/6269dbe8-9b32-4d43-b42f-81594a0a36cf"
            pdf:
              type: string
              example: "https://empresa1.demo3pro6.ibu.pe/downloads/document/pdf/6269dbe8-9b32-4d43-b42f-81594a0a36cf"
            cdr:
              type: string
              example: "https://empresa1.demo3pro6.ibu.pe/downloads/document/cdr/6269dbe8-9b32-4d43-b42f-81594a0a36cf"
        response:
          type: object
          properties:
            code:
              type: string
              example: "0"
            description:
              type: string
              example: "La Nota de Credito numero FC01-3, ha sido aceptada"
            notes:
              type: array
              example: []

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.demo3pro6.ibu.pe
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header