openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.demo3pro6.ibu.pe
tags:
  - name: api
    description: Generar Notas
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/person:
    post:
      tags:
        - api
      summary: Crear Cliente
      description: |  
        Su propósito es crear un nuevo cliente.  

        ***Ejemplo:***  
         - **Método:** POST  
         - **URL:** https://empresa1.demo3pro6.ibu.pe/api/person  
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt  
      operationId: crearCliente
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: |
            JSON RESPUESTA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - fastura_auth:
            - write
            - read 
          
# Formato Json de crear cliente
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: string
          example: 
        type:
          type: string
          example: "customers"
        identity_document_type_id:
          type: string
          example: "1"
        number:
          type: string
          example: "72346556"
        name:
          type: string
          example: "Pedro Diaz"
        trade_name:
          type: string
          example: "Nombre Comercial"
        country_id:
          type: string
          example: "PE"
        department_id:
          type: string
          example: 
        province_id:
          type: string
          example: 
        district_id:
          type: string
          example: 
        address:
          type: string
          example: "Urb Sesquicentenario Vipol Callao"
        telephone:
          type: string
          example: "954533737"
        condition:
          type: string
          example: 
        state:
          type: string
          example: 
        email:
          type: string
          example: 
        perception_agent:
          type: boolean
          example: false
        percentage_perception:
          type: number
          format: float
          example: 0
        more_address:
          type: array
          items:
            type: string
          example: []
        location_id:
          type: array
          items:
            type: string
          example: []
 
          
      required:
        - number
        - name

    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        msg:
          type: string
          example: "Cliente registrado con éxito"
        data:
          type: object
          properties:
            id:
              type: integer
              example: 55
            description:
              type: string
              example: "72346556 - Pedro Diaz"
            name:
              type: string
              example: "Pedro Diaz"
            number:
              type: string
              example: "72346556"
            identity_document_type_id:
              type: string
              example: "1"
            identity_document_type_code:
              type: string
              example: 
            address:
              type: string
              example: "Urb Sesquicentenario Vipol Callao"
            email:
              type: string
              example: 
            telephone:
              type: string
              example: "954533737"
            country_id:
              type: string
              example: "PE"
            district_id:
              type: string
              example: 
            selected:
              type: boolean
              example: false

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.demo3pro6.ibu.pe
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header