openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.demo3pro6.ibu.pe
tags:
  - name: api
    description: Generar Cotización
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
paths:
  /api/document/search-items?input=j1:
    get:
      tags:
        - api
      summary: BUSCAR PRODUCTOS
      description: |  
        Para buscar productos debe enviar por método get:
        ***Ejemplo:***  
        - **Método:** GET  
        - **URL:** https://empresa1.demo3pro6.ibu.pe/api/document/search-items?input=cod_interno_o_descripcion
        - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt
      operationId: buscarProductos
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'
        '400':
          description: Invalid status value
      security:
        - fastura_auth:
            - write:pets
            - read:pets
          
# Formato Json de LISTAR PRODUCTOS
components:
  schemas:
    Pet:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            number_full:
              type: string
              example: "COT-8"
            external_id:
              type: string
              example: "25fd5675-1ad5-4e7b-9191-9ae4b7f1dde2"
            filename:
              type: string
              example: "COT-8-20241108"
            print_a4:
              type: string
              example: "https://empresa1.demo3pro6.ibu.pe/quotations/print/25fd5675-1ad5-4e7b-9191-9ae4b7f1dde2/a4"
            print_ticket:
              type: string
              example: "https://empresa1.demo3pro6.ibu.pe/quotations/print/25fd5675-1ad5-4e7b-9191-9ae4b7f1dde2/ticket"

    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            items:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: number
                    example: 287
                  item_id:
                    type: number
                    example: 287
                  name:
                    type: string
                    example: "apk"
                  full_description:
                    type: string
                    example: "j1 - apk"
                  description:
                    type: string
                    example: "apk"
                  currency_type_id:
                    type: string
                    example: "PEN"
                  internal_id:
                    type: string
                    example: "jairote"
                  item_code:
                    type: string
                    example: "new_code"
                  currency_type_symbol:
                    type: string
                    example: "S/"
                  sale_unit_price:
                    type: string
                    example: "500.00"
                  purchase_unit_price:
                    type: number
                    example: 0
                  unit_type_id:
                    type: string
                    example: "NIU"
                  sale_affectation_igv_type_id:
                    type: string
                    example: "10"
                  purchase_affectation_igv_type_id:
                    type: string
                    example: "10"
                  calculate_quantity:
                    type: boolean
                    example: false
                  has_igv:
                    type: boolean
                    example: true
                  is_set:
                    type: boolean
                    example: false
                  aux_quantity:
                    type: number
                    example: 1
                  barcode:
                    type: string
                    example: ""
                  brand_id:
                    type: number
                    example: null
                  brand:
                    type: string
                    example: ""
                  category_id:
                    type: number
                    example: null
                  category:
                    type: string
                    example: ""
                  stock:
                    type: number
                    example: 0
                  image:
                    type: string
                    example: "https://empresa1.demo3pro6.ibu.pe/logo/imagen-no-disponible.jpg"
                  warehouses:
                    type: array
                    items:
                      type: object
                      properties:
                        warehouse_description:
                          type: string
                          example: "Almacén - Oficina Principal"
                        stock:
                          type: string
                          example: "0.0000"
                        warehouse_id:
                          type: number
                          example: 1
                  item_unit_types:
                    type: array
                    items: []
                  has_isc:
                    type: boolean
                    example: false
                  system_isc_type_id:
                    type: number
                    example: null
                  percentage_isc:
                    type: string
                    example: "0.00"

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.demo3pro6.ibu.pe
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header