openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.demo3pro6.ibu.pe
tags:
  - name: api
    description: Generar Notas
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/voided/status:
    post:
      tags:
        - api
      summary: CONSULTAR TICKET ANULACIÓN
      description: |  
        Para consultar el ticket de la anulación generada puede usar el siguiente servicio, necesitará la **url, el token, el external_id** (resumen) 
        y el **número de ticket**.  

        Cuando haya culminado este procedimiento, deberá consultar el ticket de la anulación generada, se explicará en el siguiente punto.  

        ***Ejemplo:***  
         - **Método:** POST  
         - **URL:** https://empresa1.demo3pro6.ibu.pe/api/voided  
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt  

        Cuando haya culminado este procedimiento, la anulación con las facturas o notas que lo conforman han sido aceptadas exitosamente por Sunat, 
        es decir el (los) documento(s) han sido anulados.
      operationId: consultarTicketAnulacion
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: |
            JSON RESPUESTA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - fastura_auth:
            - write
            - read 
          
# Formato Json de CONSULATAR TICKET DE ANULACIÓN
components:
  schemas:
    Pet:
      type: object
      properties:
        external_id:
          type: string
          example: "6a2fd7c4-6eb9-4868-a3ea-7ee30a4b6699"
        ticket:
          type: string
          example: "1731534443956"


    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            filename:
              type: string
              example: "20415963255-RA-20190126-1"
            external_id:
              type: string
              example: "0a1382c6-e639-46fc-a8ae-d4659b63c4bd"
        links:
          type: object
          properties:
            xml:
              type: string
              example: "http://demo26.multifacturalonew.oo:8084/downloads/voided/xml/0a1382c6-e639-46fc-a8ae-d4659b63c4bd"
            cdr:
              type: string
              example: "http://demo26.multifacturalonew.oo:8084/downloads/voided/cdr/0a1382c6-e639-46fc-a8ae-d4659b63c4bd"
        response:
          type: object
          properties:
            code:
              type: string
              example: "0"
            description:
              type: string
              example: "La Comunicación de baja RA-20190126-1, ha sido aceptada"
            notes:
              type: array
              example: []
            

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.demo3pro6.ibu.pe
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header